import { log } from "@openacp/plugin-sdk";
import type { GraphFileClient } from "./graph.js";
import * as fs from "node:fs";

const MAX_FILE_SIZE = 250 * 1024 * 1024; // 250MB Teams limit

/**
 * Download a file from a Teams attachment content URL.
 *
 * When a GraphFileClient is provided, uses authenticated Graph API download.
 * Falls back to unauthenticated fetch (works for some public URLs).
 */
export async function downloadTeamsFile(
  url: string,
  fileName: string,
  graphClient?: GraphFileClient,
): Promise<Buffer | null> {
  if (!url) return null;

  // Prefer Graph API authenticated download
  if (graphClient) {
    return graphClient.downloadFile(url, MAX_FILE_SIZE);
  }

  // Fallback: unauthenticated fetch (may fail for Teams-hosted files)
  try {
    const response = await fetch(url);
    if (!response.ok) {
      log.warn({ url: url.slice(0, 80), fileName, status: response.status }, "[media] downloadTeamsFile: HTTP error");
      return null;
    }

    const contentLength = response.headers.get("content-length");
    if (contentLength) {
      const size = parseInt(contentLength, 10);
      if (size > MAX_FILE_SIZE) {
        throw new Error(`File too large: ${size} bytes (max ${MAX_FILE_SIZE})`);
      }
    }

    const arrayBuffer = await response.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    if (buffer.length > MAX_FILE_SIZE) {
      throw new Error(`File too large: ${buffer.length} bytes (max ${MAX_FILE_SIZE})`);
    }

    return buffer;
  } catch (err) {
    if (err instanceof Error && err.message.startsWith("File too large")) {
      throw err;
    }
    log.warn({ err, fileName }, "[media] downloadTeamsFile: fetch failed (non-fatal)");
    return null;
  }
}

export function isAttachmentTooLarge(size: number): boolean {
  return size > MAX_FILE_SIZE;
}

/**
 * Upload a file to OneDrive via Graph API and return a sharing URL.
 * Returns null if Graph client is not configured or upload fails.
 */
export async function uploadFileViaGraph(
  graphClient: GraphFileClient | undefined,
  sessionId: string,
  filePath: string,
  fileName: string,
  contentType: string,
): Promise<string | null> {
  if (!graphClient) {
    log.debug("[media] No Graph client configured, skipping file upload");
    return null;
  }

  try {
    const content = await fs.promises.readFile(filePath);
    return await graphClient.uploadFile(sessionId, fileName, content, contentType);
  } catch (err) {
    log.error({ err, sessionId, fileName }, "[media] Graph upload failed");
    return null;
  }
}

/**
 * Build an Adaptive Card for a file attachment.
 *
 * When a shareUrl is available (from Graph API upload), includes a download button.
 * Otherwise shows file info with a note that Graph API is required.
 *
 * Uses Adaptive Card v1.2 for maximum mobile compatibility.
 */
export function buildFileAttachmentCard(
  fileName: string,
  size: number,
  contentType: string,
  shareUrl?: string,
): { type: "AdaptiveCard"; version: "1.2"; body: unknown[]; actions?: unknown[] } {
  const sizeStr = size >= 1024 * 1024
    ? `${(size / 1024 / 1024).toFixed(1)} MB`
    : `${(size / 1024).toFixed(1)} KB`;

  const body: unknown[] = [
    { type: "TextBlock", text: `📎 **${fileName}**`, weight: "Bolder", wrap: true },
    {
      type: "ColumnSet",
      columns: [
        {
          type: "Column",
          width: "auto",
          items: [{ type: "TextBlock", text: `Size: ${sizeStr}`, size: "Small", isSubtle: true }],
        },
        {
          type: "Column",
          width: "auto",
          items: [{ type: "TextBlock", text: `Type: ${contentType}`, size: "Small", isSubtle: true }],
        },
      ],
    },
  ];

  if (shareUrl) {
    return {
      type: "AdaptiveCard",
      version: "1.2",
      body,
      actions: [
        {
          type: "Action.OpenUrl",
          title: "Download",
          url: shareUrl,
        },
      ],
    };
  }

  body.push({
    type: "TextBlock",
    text: "_File generated by agent. Configure Graph API permissions for direct download links._",
    size: "Small",
    isSubtle: true,
    wrap: true,
  });

  return { type: "AdaptiveCard", version: "1.2", body };
}
